# Generated by Django 3.1.7 on 2021-03-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMakeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(db_index=True, max_length=32, verbose_name='make')),
                ('model', models.CharField(db_index=True, max_length=32, verbose_name='model')),
                ('slug', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='slug')),
                ('make_slug', models.CharField(db_index=True, max_length=32, verbose_name='make slug')),
                ('model_slug', models.CharField(db_index=True, max_length=32, verbose_name='model slug')),
            ],
        ),
    ]
