# Generated by Django 3.1.7 on 2021-05-17 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='part number')),
                ('part_type', models.CharField(choices=[('Part', 'Part'), ('Accessory', 'Accessory')], default='Part', max_length=16, verbose_name='type')),
                ('title', models.TextField(blank=True, null=True, verbose_name='title')),
                ('cost_price_range', models.CharField(choices=[('0-50', '0-50'), ('50-100', '50-100'), ('100-150', '100-150'), ('150-200', '150-200'), ('200-250', '200-250'), ('250-500', '250-500'), ('500+', '500+'), ('500-1000', '500-1000'), ('1000-2000', '1000-2000'), ('2000+', '2000+')], default='0-50', max_length=16, verbose_name='cost price range')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='core.manufacturer', verbose_name='manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='domain name')),
                ('is_client', models.BooleanField(default=False, verbose_name='is client')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='start date')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('manufacturers', models.ManyToManyField(blank=True, to='core.Manufacturer', verbose_name='manufacturers')),
            ],
        ),
        migrations.CreateModel(
            name='PartPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='date')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='price')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_prices', to='core.part', verbose_name='part')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_prices', to='core.website', verbose_name='website')),
            ],
        ),
        migrations.CreateModel(
            name='PartCostPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(db_index=True, verbose_name='start date')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='cost')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_cost_points', to='core.part', verbose_name='part')),
            ],
        ),
    ]
