# Generated by Django 3.1.7 on 2021-05-19 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_manufacturer_part_partcostpoint_partprice_website'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmakemodel',
            options={'verbose_name': 'Car Make/Model', 'verbose_name_plural': 'Car Make/Models'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'Manufacturer'},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'verbose_name': 'Car Part', 'verbose_name_plural': 'Car Parts'},
        ),
        migrations.AlterModelOptions(
            name='partcostpoint',
            options={'verbose_name': 'Car Part Cost', 'verbose_name_plural': 'Car Part Costs'},
        ),
        migrations.AlterModelOptions(
            name='partprice',
            options={'verbose_name': 'Car Part Price', 'verbose_name_plural': 'Car Part Prices'},
        ),
    ]
