# Generated by Django 3.1.7 on 2021-05-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210518_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='title',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='title'),
        ),
    ]
