# Generated by Django 3.1.7 on 2021-05-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_website_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='title',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='title'),
        ),
    ]
