# Generated by Django 3.1.7 on 2021-05-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210521_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='domain_name',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='domain name'),
        ),
    ]
