# Generated by Django 3.1.7 on 2021-05-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210521_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='platform',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='platform'),
        ),
        migrations.AlterField(
            model_name='website',
            name='is_active',
            field=models.BooleanField(blank=True, null=True, verbose_name='is active'),
        ),
    ]
