# Generated by Django 3.1.7 on 2021-05-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210525_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='title'),
        ),
    ]
