# Generated by Django 3.1.7 on 2021-07-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210527_1453'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='part',
            constraint=models.CheckConstraint(check=models.Q(part_type__in=('Part', 'Accessory')), name='part_type_valid'),
        ),
    ]
