# Generated by Django 3.1.7 on 2021-05-24 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_auto_20210521_1735'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteExclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_exclusions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='core.website', verbose_name='website')),
            ],
        ),
    ]
