# Generated by Django 3.1.7 on 2021-05-19 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadprogress',
            old_name='type',
            new_name='schema',
        ),
    ]
