# Generated by Django 3.1.7 on 2021-05-19 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20210518_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadprogress',
            options={'verbose_name': 'Upload tracker'},
        ),
    ]
