# Generated by Django 3.1.7 on 2021-05-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20210519_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadprogress',
            name='objects_updated',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
