# Generated by Django 3.1.7 on 2021-03-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20210323_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentsection',
            name='slot',
            field=models.CharField(choices=[('body', 'body'), ('meta1', 'meta1'), ('meta2', 'meta2'), ('header', 'header'), ('footer', 'footer')], db_index=True, default='body', max_length=24, verbose_name='slot'),
        ),
    ]
