# Generated by Django 3.1.7 on 2021-05-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20210331_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentsection',
            name='slot',
            field=models.CharField(choices=[('header', 'header'), ('meta1', 'meta1'), ('meta2', 'meta2'), ('body', 'body'), ('footer', 'footer')], db_index=True, default='body', max_length=24, verbose_name='slot'),
        ),
    ]
