# Generated by Django 3.1.7 on 2021-05-27 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20210505_1602'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Website',
        ),
    ]
