# Generated by Django 3.1.7 on 2021-02-25 18:25

import media.models
from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
      ('media', '0002_auto_20210224_1941'),
  ]

  operations = [
      migrations.AlterField(
          model_name='mediafile',
          name='file',
          field=models.FileField(upload_to="media/", verbose_name='file'),
      ),
  ]
